### ISSUE TITLE
tvOS Swipe Support?

### ISSUE THREAD

**Issue by dannycortesv** [distriqt/ANE-SystemGestures#1]
Hi Michael, would be great if this extension supports tvOS Swipe Gesture, i would pay for it. This gesture is not functional with Air implementation, you can see more about this issue here:

https://github.com/Gamua/Adobe-Runtime-Support/issues/11

**Comment by marchbold** [comment]
Will investigate. You can contact us via email if you are up for sponsoring the development.

**Comment by dannycortesv** [comment]
Thanks for your help @marchbold, Apple TV support is a great plus that keeps AIR strong. Please let me know how your research goes.

**Comment by marchbold** [comment]
Let me know how it goes and if you run into any issues.
