### ISSUE TITLE
Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by Paul-Ollivier** [distriqt/ANE-SystemGestures#2]
Hi guys,

First of, thanks for the awesome ANE's!

I've got an error compiling my app with Air SDK 31, using SystemGestures --> 

Compilation failed while executing : ld64
Packaging output: 
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_DTFREUtils", referenced from:
      objc-class-ref in libcom.distriqt.SystemGestures.a(DTSGController.o)
      objc-class-ref in libcom.distriqt.SystemGestures.a(SystemGestures.o)
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_DTFREUtils", referenced from:
      objc-class-ref in libcom.distriqt.SystemGestures.a(DTSGController.o)
      objc-class-ref in libcom.distriqt.SystemGestures.a(SystemGestures.o)
ld: symbol(s) not found for architecture arm64
ld: symbol(s) not found for architecture armv7

Am I missing something?

**Comment by marchbold** [comment]
Yeah, that indicates you haven't added the Core ANE. 

https://github.com/distriqt/ANE-SystemGestures/wiki/i.Add-the-Extension
