### ISSUE TITLE
Hide Home Bar - iPhoneX

### ISSUE THREAD

**Issue by Lydecker** [distriqt/ANE-SystemGestures#3]
On apple devices with no home button, a horizontal bar appears at the bottom of the screen (which is used to swipe up to get to the home screen).

Is there a way we can hide the bar (not disable the os functionality- just hide the bar)

Reading online it implys its the developers responsibility to hide the bar if they want to, not the users through the os settings....

**Comment by marchbold** [comment]
Are you talking about the system gestures? Have you tried the system gestures ANE? 

https://airnativeextensions.com/extension/com.distriqt.SystemGestures
