### ISSUE TITLE
Issue with detecting swipes to the right

### ISSUE THREAD

**Issue by Ender22** [distriqt/ANE-SystemGestures#8]
Hello, can I understand how this ANE is meant to be used? 

My goal was to have a way to trigger a 'go back' event in my app when the user swiped to the right from the left edge of the screen on iOS, since that is a common app practice. However, when detecting that swipe I'm getting really weird results with this ane. 

- When adding SystemGestures.service.addEventListener( NativeGestureEvent.GESTURE_SWIPE_RIGHT, myFunction); It is like overly sensitive, anytime my finger drags from left to right on the screen anywhere this is firing even if its not a normal swipe gesture, i.e. even if my finger moves really slowly, or barely moves much at all

- When the NativeGestureEvent.GESTURE_SWIPE_RIGHT fires and myFunction above triggers, my touch event gets canceled or something, for example if the user is trying to scroll a horizontal list of images... as soon as they move their finger to the right, myfunction gets trigger (which I've set up to do nothing) and then the scroll action is cancelled or something (making it physically impossible for them to scroll anything in that direction). To say it another way, the firing of the event like is the equivalent of the user lifting his finger from the screen even when he hasn't. 

I've found out I can check if event.location.x < 15 to ensure that my 'back' action only triggers if they are swiping right from the very edge of the screen, but the 2nd point, where the firing of the event is canceling all my touch events is what makes me unable to use this because there are multiple places in the app where the user needs to scroll something to the right. 

Is there anything I can do?

**Comment by marchbold** [comment]
These are tied directly to system driven events and yeah I believe even a lot of iOS developers complain that it is too sensitive. 

eg https://stackoverflow.com/questions/29666921/uiswipegesturerecognizer-swipe-left-and-finger-up

Unfortunately there's no real configuration we can do on these events, so the solution if the event is not appropriate for you is to write a custom recogniser which can equally be done in your as3 code.

I used [Gestouch](https://github.com/fljot/Gestouch) for this a long time ago, not sure if it is still applicable though.

**Comment by Ender22** [comment]
Understood, thanks
